print("Figure 1 C: Means of the Investor playing BPD Investments (Fractions): ")
Sys.sleep(1)
print(colMeans(FracInvestorWithBPD))
Sys.sleep(2)
print("Figure 1 C: Means of the Investor playing HC Investments (Fractions): ")
Sys.sleep(1)
print(colMeans(FracInvestorWithHC))
Sys.sleep(2)
print("Figure 1 C: Means of the BPD Repayments (Fractions): ")
Sys.sleep(1)
print(colMeans(FracBPDTrustee))
Sys.sleep(2)
print("Figure 1 C: Means of the HC Repayments (Fractions): ")
Sys.sleep(1)
print(colMeans(FracHCTrustee))
Sys.sleep(2)
print("Figure 1 C: Bonferroni corrected significancies between Investments: ")
Sys.sleep(1)
print(10*I_Investments)
Sys.sleep(2)
print("Figure 1 C: Bonferroni corrected significancies between Repayments: ")
Sys.sleep(1)
print(10*T_Repayments)
Sys.sleep(2)
print("Figure 1 D: Generated and Real Investments BPD: ")
Sys.sleep(1)
print(c(mean(rowSums(InvestorWithBPD)), 
           mean(rowSums(OldInvestor[1:55,]))))
Sys.sleep(2)
print("Figure 1 D: Significance Level between Generated and Real Investments BPD: ")
Sys.sleep(1)
print(permTS(rowSums(InvestorWithBPD), rowSums(OldInvestor[1:55,]), alternative = "two.sided")$p.value)
Sys.sleep(2)
print("Figure 1 D: Generated and Real Investments HC: ")
Sys.sleep(1)
print(c(mean(rowSums(InvestorWithHC)), 
        mean(rowSums(OldInvestor[56:93,]))))
Sys.sleep(2)
#print("Figure 1 D: Significance Level between Generated and Real Investments HC: ")
#Sys.sleep(1)
#print(permTS(rowSums(InvestorWithHC), rowSums(OldInvestor[56:93,]), alternative = "two.sided")$p.value)
#Sys.sleep(2)
print("Figure 1 E: Generated and Real Repayments BPD: ")
Sys.sleep(1)
print(c(mean(rowSums(BPDTrustee)), 
        mean(rowSums(OldTrustee[1:55,]))))
Sys.sleep(2)
print("Figure 1 E: Generated and Real Repayments HC: ")
Sys.sleep(1)
print(	        c(  mean(rowSums(HCTrustee)), 
                 mean(rowSums(OldTrustee[56:93,]))))
Sys.sleep(2)
print("Figure 1 F: Percentage of 0 investments on step 4:")
Sys.sleep(1)
print(	        c(  ZeroInvestmentsStep4Classic))
Sys.sleep(2)
print("Figure 1 F: Percentage of 0 investments on step 7:")
Sys.sleep(1)
print(	        c(  ZeroInvestmentsStep7Classic))
Sys.sleep(2)
print("Risk Aversion: Mean Negative LogLikelihoods Investor under the classical Model:")
Sys.sleep(1)
print(	        c(  mean(Holder$OInvestorLikelihood)))
Sys.sleep(2)
print("Risk Aversion: Mean Negative LogLikelihoods Investor under the Risk Aversion Model:")
Sys.sleep(1)
print(	        c(  mean(Holder$AvInvestorLikelihood)))
Sys.sleep(2)
print("Risk Aversion: Mean Negative LogLikelihoods Trustee under the classical Model:")
Sys.sleep(1)
print(	        c(  mean(Holder$OTrusteeLikelihood)))
Sys.sleep(2)
print("Risk Aversion: Mean Negative LogLikelihoods trustee under the Risk Aversion Model:")
Sys.sleep(1)
print(	        c(  mean(Holder$AvTrusteeLikelihood)))
Sys.sleep(2)
print("Risk Aversion: Significance of a Likelihood Ratio Test between the nested investor models:")
Sys.sleep(1)
print(p_value_Investor_Aversion)
Sys.sleep(2)
print("Risk Aversion: Significance of a Likelihood Ratio Test between the nested trustee models:")
Sys.sleep(1)
print(p_value_Trustee_Aversion)
Sys.sleep(2)
print("Risk Aversion: Mean BIC Investor under the Old Model:")
Sys.sleep(1)
print(	        c( MeanOldInvestorBIC))
Sys.sleep(2)
print("Risk Aversion: Mean BIC Investor under the Risk Aversion Model:")
Sys.sleep(1)
print(	        c( MeanRiskInvestorBIC))
Sys.sleep(2)
print("Risk Aversion: Mean BIC Trustee under the Old Model:")
Sys.sleep(1)
print(	        c( MeanOldTrusteeBIC))
Sys.sleep(2)
print("Risk Aversion: Mean BIC Trustee under the Risk Aversion Model:")
Sys.sleep(1)
print(	        c( MeanRiskTrusteeBIC))
Sys.sleep(2)
print("Irritation: Figure 2A Investments (Repair-Example):")
Sys.sleep(1)
print(	        1/4*RepairInvestor[10,])
Sys.sleep(2)
print("Irritation: Figure 2A Repayments (Repair-Example):")
Sys.sleep(1)
print(	        1/6*RepairTrustee[10,])
Sys.sleep(2)
print("Irritation: Figure 2A State-Shifts (Repair-Example):")
Sys.sleep(1)
print(	        Shift[10,])
Sys.sleep(2)
print("Irritation: Figure 2B Investments (Break-Example):")
Sys.sleep(1)
print(	        1/4*BreakInvestor[1,])
Sys.sleep(2)
print("Irritation: Figure 2B Repayments (Break-Example):")
Sys.sleep(1)
print(	        1/6*BreakTrustee[1,])
Sys.sleep(2)
print("Irritation: Figure 2B State-Shifts (Break-Example):")
Sys.sleep(1)
print(	        BreakShift[1,])
Sys.sleep(2)
print("Irritation model: Mean Choice Prediction Investor:")
Sys.sleep(1)
print(ProbabilityFinal)
Sys.sleep(2)
print("Irritation model: Mean Negative LogLikelihoods Investor:")
Sys.sleep(1)
print(MeanFinal)
Sys.sleep(2)
print("Irritation model: Mean Negative LogLikelihoods Trustee:")
Sys.sleep(1)
print(MeanFinalTrust)
Sys.sleep(2)
print("Irritation model: Mean Choice Prediction Trustee:")
Sys.sleep(1)
print(ProbabilityFinalTrust)
Sys.sleep(2)
print("Irritation Model: Significance of a Likelihood Ratio Test between the nested investor models:")
Sys.sleep(1)
print(p_value_Investor_Full_Model)
Sys.sleep(2)
print("Irritation Model: Significance of a Likelihood Ratio Test between the nested trustee models:")
Sys.sleep(1)
print(p_value_Trustee_Full_Model)
Sys.sleep(2)
print("Irritation Model: Mean BIC Investor under the Final Model:")
Sys.sleep(1)
print(	        c(MeanFinalBIC))
Sys.sleep(2)
print("Irritation Model: Mean BIC Trustee under the Final Model:")
Sys.sleep(1)
print(	        c( MeanFinalTrustBIC))
Sys.sleep(2)
print("Figure 2 E: Percentage of 0 investments on step 4:")
Sys.sleep(1)
print(	        c(  ZeroInvestmentsStep4Final))
Sys.sleep(2)
print("Figure 2 E: Percentage of 0 investments on step 7:")
Sys.sleep(1)
print(	        c(  ZeroInvestmentsStep7Final))
Sys.sleep(2)
print("Figure 2 E: NLL of Investor under Risk Aversion and Full Model respectively:" )
Sys.sleep(1)
print(	        c(Holder$AvInvestorLikelihood[29] ,FinalParams$Data.FInvestorLikelihoods[29]))
Sys.sleep(2)
print("Figure 2 F: NLL of Trustee under Risk Aversion and Full Model respectively:" )
Sys.sleep(1)
print(	        c(Holder$AvTrusteeLikelihood[29] ,FinalParams$Data.FTrusteeLikelihoods[29]))
Sys.sleep(2)
print("Behavioural Analysis: Signficance of Trustee Guilt Differences under Final Model:" )
Sys.sleep(1)
print(	      p_trustee_guilt)
Sys.sleep(2)
print("Behavioural Analysis: Signficance of Investor Planning Differences under Final Model:" )
Sys.sleep(1)
print(	    p_investor_plan)
Sys.sleep(2)
print("Behavioural Analysis: Signficance of Trustee Guilt = 0 Proportion:" )
Sys.sleep(1)
print(	     GuiltProportion)
Sys.sleep(2)
print("Behavioural Analysis: Signficance of Trustee Awareness = 0 Proportion:" )
Sys.sleep(1)
print(	    AwarenessProportion)
Sys.sleep(2)
print("Behavioural Analysis: Signficance of Trustee Perilousness Proportion (uncorrected):" )
Sys.sleep(1)
print(	PerilousProportion)
Sys.sleep(2)
print("Behavioural Analysis: Frequency of Perilousness in BPDs:" )
Sys.sleep(1)
print(sum(BPDTrusteeShift == 0 | BPDTrusteeGuilt == 0)/55)
Sys.sleep(2)
print("Behavioural Analysis: Frequency of Perilousness in HCs:" )
Sys.sleep(1)
print(sum(HCTrusteeShift == 0 | HCTrusteeGuilt == 0)/38)
Sys.sleep(2)
print("Figure 4 A:uncorrected significancies between Investments Perilous: ")
Sys.sleep(1)
print(Perilous_Investments)
Sys.sleep(2)
print("Figure 4 A:uncorrected significancies between Repayments Perilous: ")
Sys.sleep(1)
print(Perilous_Repayments)
Sys.sleep(2)
print("Figure 4 B: uncorrected significancies between Investments NonPerilous: ")
Sys.sleep(1)
print(Non_Perilous_Investments)
Sys.sleep(2)
print("Figure 4 B: uncorrected significancies between Repayments NonPerilous: ")
Sys.sleep(1)
print(Non_Perilous_Repayments)
Sys.sleep(2)